version: '2'

services:
  web_server:
    image: keymetrics/pm2:8-alpine
    ports:
      - ${WEB_SERVER_PORT}:8080
    depends_on:
      - mysql
    container_name: gestor-incidencies-webserver
    working_dir: /web
    command: npm start
    volumes:
      - ./parts_incidencia:/web
  mysql:
    image: mysql:8.0.1
    container_name: gestor-incidencies-mysql
    #restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - TZ=UTC
    volumes:
     - ./data/db/mysql:/var/lib/mysql
     - ./mysql.cnf:/etc/mysql/my.cnf
